#!/usr/bin/env python3
"""Reconstruct the corpus source frame and analyze normalized detector output."""

import argparse
import ast
import csv
import glob
import hashlib
import json
import math
import statistics
from collections import Counter, defaultdict
from pathlib import Path


EXPECTED_REPOSITORIES = 602
EXPECTED_EXCLUDED_DIRECTORIES = 43
HISTORICAL_REPORTED_FILES = 17_450
EXPECTED_SOURCE_LOCATIONS = {
    "src": 17_314,
    "target/generated-sources": 360,
    "other": 314,
}
EXPECTED_UNIQUE_FILES = 17_988
EXPECTED_FLAGS = 15_931
EXPECTED_RULE_SHA256 = "0e76695e8ff0705d6b8db74c500539d707926cbc8cb4df658ad4507d9d261b7b"
SOURCE_ROLES = ("generated schema", "application/query source")
SMALL_MAX_FILES = 31
MEDIUM_MAX_FILES = 94
OVERALL_LABEL = "Any retained class [broad detector-output density]"

CLASS_SOURCE_ROLES = (
    ("Implicit Columns", "application/query source"),
    ("ID Required", "generated schema"),
    ("Keyless Entry", "generated schema"),
    ("Fear of the Unknown", "generated schema"),
    ("Fear of the Unknown", "application/query source"),
    ("31 Flavors", "generated schema"),
    ("Poor Man's Search Engine", "application/query source"),
    ("Rounding Errors", "generated schema"),
)

EXCLUDED_PATH_FRAGMENTS = (
    "module-info.java",
    "package-info.java",
    "information_schema/InformationSchema.java",
    "information_schema/tables",
    "mysql/Mysql.java",
    "mysql/tables",
    "performance_schema/PerformanceSchema.java",
    "performance_schema/tables",
    "sys/Sys.java",
    "sys/tables",
    "FlywaySchemaHistory.java",
    "Databasechangelog.java",
    "Databasechangeloglock.java",
    "information_schema/Domains.java",
    "pg_catalog/PgCatalog.java",
    "pg_catalog/tables",
    "tables/Qrtz",
    "PgpArmorHeaders.java",
    "tables/Dblink",
    "tables/Each.java",
    "tables/Skeys.java",
    "tables/Svals.java",
)
INCLUDED_PHRASES = ("org.jooq", "Tables", "tables")
EXCLUDED_PHRASES = (
    "extends TableRecordImpl",
    "extends UpdatableRecordImpl",
    "extends org.jooq.impl.UpdatableRecordImpl",
    "extends CatalogImpl",
    "extends SchemaImpl",
    "extends UDTImpl",
    "extends UDTRecordImpl",
    "extends DAOImpl",
    "extends AbstractRoutine",
    "implements EnumType",
    "implements DeserializableJooqEnum",
    "public class Indexes",
    "public class Keys",
    "public class Routines",
    "public class Sequences",
    "public class Tables",
    "public class Domains",
    "class AbstractSpringDAOImpl",
    "extends AbstractSpringDAOImpl",
    "tables.pojos;",
    "tables.interfaces;",
    "Targeted by JavaCPP",
)
DDL_INDICATOR_PHRASES = (
    "This class is generated by jOOQ",
    "extends TableImpl",
    "extends org.jooq.impl.TableImpl",
)
RULE_NAMES = ("excluded_path_fragments", "included_phrases", "excluded_phrases")
NOTEBOOKS = (
    "25-count-relevant-files-in-full-set.ipynb",
    "051-select-sample-projects-corrected.ipynb",
    "09-evaluate-prompting-strategy.ipynb",
    "11-select-files-for-reannotation.ipynb",
    "23-count-relevant-files-in-validation-set.ipynb",
    "24-count-relevant-files-in-test-set.ipynb",
)
MANIFEST_FIELDS = (
    "repository",
    "relative_path",
    "source_location",
    "source_role",
    "bytes",
    "nonblank_loc",
    "sha256",
)
ALIGNMENT_FIELDS = (
    "flag_row",
    "repository",
    "project",
    "antipattern",
    "relative_path",
    "line_from",
    "line_to",
    "source_role",
    "source_sha256",
    "source_file_exists",
    "in_source_manifest",
    "source_frame_status",
    "span_in_bounds",
    "fragment_alignment",
    "fragment_found_in_source_file",
)
PROJECT_RESULT_FIELDS = (
    "Project",
    "Antipattern",
    "File",
    "Line from",
    "Line to",
    "Code fragment",
    "Explanation",
)
PHASE2_REPOSITORY_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "repository",
    "eligible_files",
    "flags",
    "flagged_files",
    "percent_eligible_files_flagged",
    "flags_per_100_eligible_files",
    "flags_per_flagged_file",
)
PHASE2_SUMMARY_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "repositories",
    "repositories_with_eligible_files",
    "flagged_repositories",
    "total_flags",
    "eligible_files",
    "unique_flagged_files",
    "all_relevant_files",
    "percent_eligible_files_flagged",
    "flags_per_100_eligible_files",
    "flags_per_flagged_file",
    "broad_flags_per_100_all_relevant_files",
    "repository_q1_percent_eligible_files_flagged",
    "repository_median_percent_eligible_files_flagged",
    "repository_q3_percent_eligible_files_flagged",
    "repository_q1_flags_per_100_eligible_files",
    "repository_median_flags_per_100_eligible_files",
    "repository_q3_flags_per_100_eligible_files",
    "flagged_repository_q1_flags_per_flagged_file",
    "flagged_repository_median_flags_per_flagged_file",
    "flagged_repository_q3_flags_per_flagged_file",
)
PHASE3_DENSITY_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "scope",
    "repositories",
    "repositories_with_eligible_files",
    "flagged_repositories",
    "total_flags",
    "eligible_files",
    "pooled_flags_per_100_eligible_files",
    "repository_equal_mean_flags_per_100_eligible_files",
    "repository_p10_flags_per_100_eligible_files",
    "repository_q1_flags_per_100_eligible_files",
    "repository_median_flags_per_100_eligible_files",
    "repository_q3_flags_per_100_eligible_files",
    "repository_p90_flags_per_100_eligible_files",
    "spearman_raw_flags_vs_eligible_files",
)
PHASE3_CONCENTRATION_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "flagged_repositories",
    "top_decile_repositories",
    "cutoff_flags",
    "repositories_tied_at_cutoff",
    "cutoff_ties_included",
    "total_flags",
    "top_decile_flags",
    "top_decile_flag_share_percent",
    "eligible_files",
    "top_decile_eligible_files",
    "top_decile_eligible_file_share_percent",
    "top_decile_eligible_file_share_min_percent",
    "top_decile_eligible_file_share_max_percent",
    "top_decile_flags_per_100_eligible_files",
    "remaining_flags",
    "remaining_eligible_files",
    "remaining_flags_per_100_eligible_files",
    "top_to_remaining_density_ratio",
    "top_to_remaining_density_ratio_min",
    "top_to_remaining_density_ratio_max",
)
PHASE4_CLASS_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "raw_rows",
    "canonical_events",
    "exact_content_events",
    "representative_copy_min_events",
    "representative_copy_max_events",
    "raw_eligible_files",
    "unique_file_contents",
    "raw_flagged_files",
    "unique_flagged_contents",
    "representative_copy_min_flagged_contents",
    "representative_copy_max_flagged_contents",
    "raw_percent_eligible_files_flagged",
    "exact_content_percent_flagged",
    "raw_flags_per_100_eligible_files",
    "canonical_events_per_100_eligible_files",
    "exact_content_events_per_100_contents",
    "raw_flags_per_flagged_file",
    "canonical_events_per_flagged_file",
    "exact_content_events_per_flagged_content",
)


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rule_values():
    return {
        "excluded_path_fragments": EXCLUDED_PATH_FRAGMENTS,
        "included_phrases": INCLUDED_PHRASES,
        "excluded_phrases": EXCLUDED_PHRASES,
    }


def rule_digest(rules):
    payload = json.dumps(rules, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()


def notebook_values(path):
    values = {}
    notebook = json.loads(path.read_text(encoding="utf-8"))
    for cell in notebook["cells"]:
        try:
            tree = ast.parse("".join(cell.get("source", ())))
        except SyntaxError:
            continue
        for node in tree.body:
            if not isinstance(node, ast.Assign) or len(node.targets) != 1:
                continue
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in (*RULE_NAMES, "ddl_indicator_phrases"):
                values[target.id] = tuple(ast.literal_eval(node.value))
    return values


def read_allowlist(path):
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    names = [row["name"] for row in rows]
    assert len(names) == EXPECTED_REPOSITORIES, f"expected 602 repositories, found {len(names)}"
    assert len(set(names)) == len(names), "allowlist repository names are not unique"
    return names


def source_location(relative_path):
    parts = Path(relative_path).parts
    if any(
        parts[index : index + 2] == ("target", "generated-sources")
        for index in range(len(parts) - 1)
    ):
        return "target/generated-sources"
    return "src" if "src" in parts else "other"


def source_row(name, project, path):
    relative_path = path.relative_to(project).as_posix()
    if not path.is_file() or any(part in relative_path for part in EXCLUDED_PATH_FRAGMENTS):
        return None
    raw = path.read_bytes()
    text = decode_java(raw)
    if not any(phrase in text for phrase in INCLUDED_PHRASES):
        return None
    if any(phrase in text for phrase in EXCLUDED_PHRASES):
        return None
    return {
        "repository": name,
        "relative_path": relative_path,
        "source_location": source_location(relative_path),
        "source_role": (
            "generated schema"
            if any(phrase in text for phrase in DDL_INDICATOR_PHRASES)
            else "application/query source"
        ),
        "bytes": len(raw),
        "nonblank_loc": sum(bool(line.strip()) for line in text.splitlines()),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }


def select_detector_sources(repositories, names):
    manifest = {}
    for name in names:
        project = repositories / name.replace("/", "_")
        for filename in glob.glob(str(project / "**/*.java"), recursive=True):
            row = source_row(name, project, Path(filename))
            if row is not None:
                manifest[(name, row["relative_path"])] = row
    return sorted(manifest.values(), key=lambda row: (row["repository"], row["relative_path"]))


def read_manifest(path, repositories):
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        assert tuple(reader.fieldnames or ()) == MANIFEST_FIELDS
        rows = list(reader)
    manifest = {(row["repository"], row["relative_path"]): row for row in rows}
    assert len(manifest) == EXPECTED_UNIQUE_FILES
    refreshed = []
    for repository, relative_path in manifest:
        project = repositories / repository.replace("/", "_")
        row = source_row(repository, project, project / relative_path)
        assert row is not None, f"manifest file no longer passes detector filters: {project / relative_path}"
        refreshed.append(row)
    return sorted(refreshed, key=lambda row: (row["repository"], row["relative_path"]))


def decode_java(raw):
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw.decode("cp1252", errors="replace")


def normalize_whitespace(text):
    return " ".join(text.split())


def fragment_alignment(fragment, span):
    if fragment.strip() == span.strip():
        return "trimmed_exact"
    fragment = normalize_whitespace(fragment)
    span = normalize_whitespace(span)
    if fragment == span:
        return "whitespace_normalized_exact"
    if fragment and fragment in span:
        return "archived_fragment_within_span"
    if span and span in fragment:
        return "source_span_within_archived_fragment"
    return "mismatch"


def source_frame_status(path, relative_path, contents, source):
    if source is not None:
        return source["source_location"]
    reasons = []
    if "src" not in Path(relative_path).parts:
        reasons.append("outside_src_tree")
    if any(part in str(path) for part in EXCLUDED_PATH_FRAGMENTS):
        reasons.append("excluded_path_fragment")
    if not any(phrase in contents for phrase in INCLUDED_PHRASES):
        reasons.append("missing_included_phrase")
    if any(phrase in contents for phrase in EXCLUDED_PHRASES):
        reasons.append("contains_excluded_phrase")
    return "+".join(reasons) or "unexplained"


def align_flags(path, repositories, name_to_project, manifest):
    by_source = {(row["repository"], row["relative_path"]): row for row in manifest}
    text_cache = {}
    alignments = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        frozen_fields = tuple(reader.fieldnames or ())
        flags = list(reader)
    assert len(flags) == EXPECTED_FLAGS, f"expected 15,931 flags, found {len(flags)}"

    for flag_row, row in enumerate(flags, 1):
        name = row["project_name"]
        project_name = row["Project"]
        relative_path = Path(row["File"]).as_posix()
        expected_project = name_to_project.get(name)
        source = by_source.get((name, relative_path))
        in_manifest = source is not None and expected_project == project_name
        exists = False
        span_ok = False
        alignment = "not_checked"
        fragment_in_file = False
        frame_status = "not_checked"
        source_role = ""
        source_hash = ""
        if expected_project == project_name:
            project = repositories / project_name
            candidate = project / relative_path
            try:
                source_path = candidate.resolve(strict=True)
            except FileNotFoundError:
                source_path = None
            if source_path is not None:
                assert source_path.is_relative_to(project.resolve()), f"path escapes repository: {source_path}"
                exists = source_path.is_file()
            if exists:
                if source_path not in text_cache:
                    raw = source_path.read_bytes()
                    decoded_text = decode_java(raw)
                    text_cache[source_path] = (
                        decoded_text.splitlines(),
                        normalize_whitespace(decoded_text),
                        hashlib.sha256(raw).hexdigest(),
                        (
                            "generated schema"
                            if any(phrase in decoded_text for phrase in DDL_INDICATOR_PHRASES)
                            else "application/query source"
                        ),
                        source_frame_status(source_path, relative_path, decoded_text, source),
                    )
                lines, normalized_source, source_hash, source_role, frame_status = text_cache[source_path]
                normalized_fragment = normalize_whitespace(row["Code fragment"])
                fragment_in_file = bool(normalized_fragment and normalized_fragment in normalized_source)
                line_from = int(row["Line from"])
                line_to = int(row["Line to"])
                span_ok = 1 <= line_from <= line_to <= len(lines)
                if span_ok:
                    alignment = fragment_alignment(
                        row["Code fragment"], "\n".join(lines[line_from - 1 : line_to])
                    )
        alignments.append(
            {
                "flag_row": flag_row,
                "repository": name,
                "project": project_name,
                "antipattern": row["Antipattern"],
                "relative_path": relative_path,
                "line_from": row["Line from"],
                "line_to": row["Line to"],
                "source_role": source_role,
                "source_sha256": source_hash,
                "source_file_exists": str(exists).lower(),
                "in_source_manifest": str(in_manifest).lower(),
                "source_frame_status": frame_status,
                "span_in_bounds": str(span_ok).lower(),
                "fragment_alignment": alignment,
                "fragment_found_in_source_file": str(fragment_in_file).lower(),
            }
        )
    return frozen_fields, flags, alignments


def reproduce_merged_results(project_results, names, name_to_project, frozen_fields, flags):
    expected_paths = {project_results / f"{name_to_project[name]}.csv" for name in names}
    actual_paths = set(project_results.glob("*.csv"))
    assert actual_paths == expected_paths, "per-project result files do not match the allowlist"
    reconstructed = []
    hashes = {}
    for name in names:
        path = project_results / f"{name_to_project[name]}.csv"
        hashes[path.name] = sha256(path)
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            assert tuple(reader.fieldnames or ()) == PROJECT_RESULT_FIELDS, f"unexpected header: {path}"
            for row in reader:
                reconstructed.append((name, *(row[field] for field in PROJECT_RESULT_FIELDS)))
    frozen = [tuple(row[field] for field in frozen_fields) for row in flags]
    return Counter(reconstructed) == Counter(frozen), hashes


def format_rate(numerator, denominator, multiplier=1):
    return "" if not denominator else f"{multiplier * numerator / denominator:.6f}"


def quartiles(values):
    q1, _, q3 = statistics.quantiles(values, n=4, method="inclusive")
    return q1, statistics.median(values), q3


def size_stratum(file_count):
    if file_count <= SMALL_MAX_FILES:
        return "small"
    return "medium" if file_count <= MEDIUM_MAX_FILES else "large"


def density_summary(rows, scope):
    eligible_rows = [row for row in rows if row["eligible_files"]]
    densities = [100 * row["flags"] / row["eligible_files"] for row in eligible_rows]
    deciles = statistics.quantiles(densities, n=10, method="inclusive")
    q1, median, q3 = quartiles(densities)
    file_counts = [row["eligible_files"] for row in rows]
    flag_counts = [row["flags"] for row in rows]
    correlation = (
        statistics.correlation(file_counts, flag_counts, method="ranked")
        if len(set(file_counts)) > 1 and len(set(flag_counts)) > 1
        else None
    )
    return {
        "analysis_label": rows[0]["analysis_label"],
        "antipattern": rows[0]["antipattern"],
        "eligible_source_role": rows[0]["eligible_source_role"],
        "scope": scope,
        "repositories": len(rows),
        "repositories_with_eligible_files": len(eligible_rows),
        "flagged_repositories": sum(bool(row["flags"]) for row in rows),
        "total_flags": sum(flag_counts),
        "eligible_files": sum(file_counts),
        "pooled_flags_per_100_eligible_files": format_rate(
            sum(flag_counts), sum(file_counts), 100
        ),
        "repository_equal_mean_flags_per_100_eligible_files": f"{statistics.mean(densities):.6f}",
        "repository_p10_flags_per_100_eligible_files": f"{deciles[0]:.6f}",
        "repository_q1_flags_per_100_eligible_files": f"{q1:.6f}",
        "repository_median_flags_per_100_eligible_files": f"{median:.6f}",
        "repository_q3_flags_per_100_eligible_files": f"{q3:.6f}",
        "repository_p90_flags_per_100_eligible_files": f"{deciles[-1]:.6f}",
        "spearman_raw_flags_vs_eligible_files": (
            "" if correlation is None else f"{correlation:.6f}"
        ),
    }


def phase3_tables(repository_rows, manifest):
    corpus_files = Counter(row["repository"] for row in manifest)
    by_label = defaultdict(list)
    for row in repository_rows:
        by_label[row["analysis_label"]].append(row)

    density_rows = []
    concentration_rows = []
    selected_top_deciles = {}
    for label, rows in by_label.items():
        flagged_rows = [row for row in rows if row["flags"]]
        top_count = math.ceil(len(flagged_rows) * 0.10)
        ranked = sorted(flagged_rows, key=lambda row: (-row["flags"], row["repository"]))
        top_rows = ranked[:top_count]
        top_repositories = {row["repository"] for row in top_rows}
        selected_top_deciles[label] = top_repositories
        remaining_rows = [row for row in rows if row["repository"] not in top_repositories]
        cutoff = top_rows[-1]["flags"]
        tied = sum(row["flags"] == cutoff for row in flagged_rows)
        included_ties = sum(row["flags"] == cutoff for row in top_rows)
        above_cutoff = [row for row in flagged_rows if row["flags"] > cutoff]
        cutoff_rows = [row for row in flagged_rows if row["flags"] == cutoff]
        total_flags = sum(row["flags"] for row in rows)
        total_files = sum(row["eligible_files"] for row in rows)
        top_flags = sum(row["flags"] for row in top_rows)
        top_files = sum(row["eligible_files"] for row in top_rows)
        remaining_flags = sum(row["flags"] for row in remaining_rows)
        remaining_files = sum(row["eligible_files"] for row in remaining_rows)
        top_density = 100 * top_flags / top_files
        remaining_density = 100 * remaining_flags / remaining_files
        fixed_top_files = sum(row["eligible_files"] for row in above_cutoff)
        tied_file_counts = sorted(row["eligible_files"] for row in cutoff_rows)
        min_top_files = fixed_top_files + sum(tied_file_counts[:included_ties])
        max_top_files = fixed_top_files + sum(tied_file_counts[-included_ties:])
        min_density_ratio = (top_flags / max_top_files) / (
            remaining_flags / (total_files - max_top_files)
        )
        max_density_ratio = (top_flags / min_top_files) / (
            remaining_flags / (total_files - min_top_files)
        )

        concentration_rows.append(
            {
                "analysis_label": label,
                "antipattern": rows[0]["antipattern"],
                "eligible_source_role": rows[0]["eligible_source_role"],
                "flagged_repositories": len(flagged_rows),
                "top_decile_repositories": top_count,
                "cutoff_flags": cutoff,
                "repositories_tied_at_cutoff": tied,
                "cutoff_ties_included": included_ties,
                "total_flags": total_flags,
                "top_decile_flags": top_flags,
                "top_decile_flag_share_percent": format_rate(top_flags, total_flags, 100),
                "eligible_files": total_files,
                "top_decile_eligible_files": top_files,
                "top_decile_eligible_file_share_percent": format_rate(
                    top_files, total_files, 100
                ),
                "top_decile_eligible_file_share_min_percent": format_rate(
                    min_top_files, total_files, 100
                ),
                "top_decile_eligible_file_share_max_percent": format_rate(
                    max_top_files, total_files, 100
                ),
                "top_decile_flags_per_100_eligible_files": f"{top_density:.6f}",
                "remaining_flags": remaining_flags,
                "remaining_eligible_files": remaining_files,
                "remaining_flags_per_100_eligible_files": f"{remaining_density:.6f}",
                "top_to_remaining_density_ratio": f"{top_density / remaining_density:.6f}",
                "top_to_remaining_density_ratio_min": f"{min_density_ratio:.6f}",
                "top_to_remaining_density_ratio_max": f"{max_density_ratio:.6f}",
            }
        )
        scopes = [
            ("all repositories", rows),
            ("excluding highest-count decile", remaining_rows),
        ]
        scopes.extend(
            (
                f"{stratum} repositories",
                [
                    row
                    for row in rows
                    if size_stratum(corpus_files[row["repository"]]) == stratum
                ],
            )
            for stratum in ("small", "medium", "large")
        )
        density_rows.extend(density_summary(scope_rows, scope) for scope, scope_rows in scopes)
    return density_rows, concentration_rows, selected_top_deciles


def phase2_tables(names, manifest, alignments):
    all_relevant_files = len(manifest)
    eligible = Counter((row["repository"], row["source_role"]) for row in manifest)
    flags = Counter(
        (row["repository"], row["antipattern"], row["source_role"])
        for row in alignments
    )
    flagged_files = defaultdict(set)
    for row in alignments:
        flagged_files[(row["repository"], row["antipattern"], row["source_role"])].add(
            row["relative_path"]
        )

    units = [
        (f"{antipattern} [{role}]", antipattern, role)
        for antipattern, role in CLASS_SOURCE_ROLES
    ]
    units.append(
        (
            OVERALL_LABEL,
            "Any retained class",
            "all relevant files",
        )
    )
    repository_rows = []
    summary_rows = []
    for label, antipattern, role in units:
        rows = []
        for repository in names:
            if role == "all relevant files":
                file_count = sum(eligible[repository, source_role] for source_role in SOURCE_ROLES)
                flag_count = sum(
                    count
                    for (repo, _, _), count in flags.items()
                    if repo == repository
                )
                flagged = {
                    path
                    for (repo, _, _), paths in flagged_files.items()
                    if repo == repository
                    for path in paths
                }
            else:
                file_count = eligible[repository, role]
                flag_count = flags[repository, antipattern, role]
                flagged = flagged_files[repository, antipattern, role]
            row = {
                "analysis_label": label,
                "antipattern": antipattern,
                "eligible_source_role": role,
                "repository": repository,
                "eligible_files": file_count,
                "flags": flag_count,
                "flagged_files": len(flagged),
                "percent_eligible_files_flagged": format_rate(len(flagged), file_count, 100),
                "flags_per_100_eligible_files": format_rate(flag_count, file_count, 100),
                "flags_per_flagged_file": format_rate(flag_count, len(flagged)),
            }
            rows.append(row)
            repository_rows.append(row)

        eligible_rows = [row for row in rows if row["eligible_files"]]
        flagged_rows = [row for row in rows if row["flagged_files"]]
        breadth = [
            100 * row["flagged_files"] / row["eligible_files"] for row in eligible_rows
        ]
        density = [100 * row["flags"] / row["eligible_files"] for row in eligible_rows]
        repetition = [row["flags"] / row["flagged_files"] for row in flagged_rows]
        breadth_q1, breadth_median, breadth_q3 = quartiles(breadth)
        density_q1, density_median, density_q3 = quartiles(density)
        repetition_q1, repetition_median, repetition_q3 = quartiles(repetition)
        total_flags = sum(row["flags"] for row in rows)
        total_files = sum(row["eligible_files"] for row in rows)
        total_flagged_files = sum(row["flagged_files"] for row in rows)
        summary_rows.append(
            {
                "analysis_label": label,
                "antipattern": antipattern,
                "eligible_source_role": role,
                "repositories": len(rows),
                "repositories_with_eligible_files": len(eligible_rows),
                "flagged_repositories": len(flagged_rows),
                "total_flags": total_flags,
                "eligible_files": total_files,
                "unique_flagged_files": total_flagged_files,
                "all_relevant_files": all_relevant_files,
                "percent_eligible_files_flagged": format_rate(total_flagged_files, total_files, 100),
                "flags_per_100_eligible_files": format_rate(total_flags, total_files, 100),
                "flags_per_flagged_file": format_rate(total_flags, total_flagged_files),
                "broad_flags_per_100_all_relevant_files": format_rate(
                    total_flags, all_relevant_files, 100
                ),
                "repository_q1_percent_eligible_files_flagged": f"{breadth_q1:.6f}",
                "repository_median_percent_eligible_files_flagged": f"{breadth_median:.6f}",
                "repository_q3_percent_eligible_files_flagged": f"{breadth_q3:.6f}",
                "repository_q1_flags_per_100_eligible_files": f"{density_q1:.6f}",
                "repository_median_flags_per_100_eligible_files": f"{density_median:.6f}",
                "repository_q3_flags_per_100_eligible_files": f"{density_q3:.6f}",
                "flagged_repository_q1_flags_per_flagged_file": f"{repetition_q1:.6f}",
                "flagged_repository_median_flags_per_flagged_file": f"{repetition_median:.6f}",
                "flagged_repository_q3_flags_per_flagged_file": f"{repetition_q3:.6f}",
            }
        )
    return repository_rows, summary_rows


def phase4_tables(names, manifest, alignments):
    content_counts = Counter(row["sha256"] for row in manifest)
    content_roles = defaultdict(set)
    for row in manifest:
        content_roles[row["sha256"]].add(row["source_role"])
    assert all(len(roles) == 1 for roles in content_roles.values())
    role_by_content = {digest: next(iter(roles)) for digest, roles in content_roles.items()}

    canonical_events = {}
    for row in alignments:
        key = (
            row["repository"],
            row["relative_path"],
            row["antipattern"],
            row["source_role"],
            row["line_from"],
            row["line_to"],
        )
        canonical_events.setdefault(key, row)

    exact_event_occurrences = defaultdict(list)
    for row in canonical_events.values():
        key = (
            row["source_sha256"],
            row["antipattern"],
            row["source_role"],
            row["line_from"],
            row["line_to"],
        )
        exact_event_occurrences[key].append(row)

    events_by_file = defaultdict(set)
    for row in canonical_events.values():
        events_by_file[row["repository"], row["relative_path"]].add(
            (
                row["antipattern"],
                row["source_role"],
                row["line_from"],
                row["line_to"],
            )
        )
    files_by_content = defaultdict(list)
    for row in manifest:
        files_by_content[row["sha256"]].append(
            (row["repository"], row["relative_path"])
        )
    representative_min_events = Counter()
    representative_max_events = Counter()
    representative_min_flagged = Counter()
    representative_max_flagged = Counter()
    inconsistent_duplicate_groups = 0
    partially_observed_exact_events = 0
    groups_with_flagged_and_unflagged_copies = 0
    for files in files_by_content.values():
        event_sets = [events_by_file[file] for file in files]
        if len(files) > 1 and len({frozenset(events) for events in event_sets}) > 1:
            inconsistent_duplicate_groups += 1
        if len(files) > 1 and any(event_sets) and any(not events for events in event_sets):
            groups_with_flagged_and_unflagged_copies += 1
        union_events = set().union(*event_sets)
        partially_observed_exact_events += sum(
            sum(event in events for events in event_sets) < len(event_sets)
            for event in union_events
        )
        total_counts = [len(events) for events in event_sets]
        representative_min_events[OVERALL_LABEL] += min(total_counts)
        representative_max_events[OVERALL_LABEL] += max(total_counts)
        representative_min_flagged[OVERALL_LABEL] += bool(min(total_counts))
        representative_max_flagged[OVERALL_LABEL] += bool(max(total_counts))
        for class_role in CLASS_SOURCE_ROLES:
            counts = [
                sum(event[:2] == class_role for event in events)
                for events in event_sets
            ]
            representative_min_events[class_role] += min(counts)
            representative_max_events[class_role] += max(counts)
            representative_min_flagged[class_role] += bool(min(counts))
            representative_max_flagged[class_role] += bool(max(counts))

    raw_eligible = Counter(row["source_role"] for row in manifest)
    exact_eligible = Counter(role_by_content.values())
    raw_flags = Counter(
        (row["antipattern"], row["source_role"]) for row in alignments
    )
    canonical_flags = Counter(
        (row["antipattern"], row["source_role"])
        for row in canonical_events.values()
    )
    exact_flags = Counter(
        (antipattern, role)
        for _, antipattern, role, _, _ in exact_event_occurrences
    )
    raw_flagged = defaultdict(set)
    for row in alignments:
        raw_flagged[row["antipattern"], row["source_role"]].add(
            (row["repository"], row["relative_path"])
        )
    exact_flagged = defaultdict(set)
    for digest, antipattern, role, _, _ in exact_event_occurrences:
        exact_flagged[antipattern, role].add(digest)

    units = [
        (f"{antipattern} [{role}]", antipattern, role)
        for antipattern, role in CLASS_SOURCE_ROLES
    ]
    units.append((OVERALL_LABEL, "Any retained class", "all relevant files"))
    class_rows = []
    for label, antipattern, role in units:
        if role == "all relevant files":
            representative_key = OVERALL_LABEL
            raw_row_count = len(alignments)
            canonical_count = len(canonical_events)
            exact_count = len(exact_event_occurrences)
            raw_file_count = len(manifest)
            exact_file_count = len(content_counts)
            raw_flagged_count = len(
                {(row["repository"], row["relative_path"]) for row in alignments}
            )
            exact_flagged_count = len(
                {row["source_sha256"] for row in canonical_events.values()}
            )
        else:
            key = (antipattern, role)
            representative_key = key
            raw_row_count = raw_flags[key]
            canonical_count = canonical_flags[key]
            exact_count = exact_flags[key]
            raw_file_count = raw_eligible[role]
            exact_file_count = exact_eligible[role]
            raw_flagged_count = len(raw_flagged[key])
            exact_flagged_count = len(exact_flagged[key])
        class_rows.append(
            {
                "analysis_label": label,
                "antipattern": antipattern,
                "eligible_source_role": role,
                "raw_rows": raw_row_count,
                "canonical_events": canonical_count,
                "exact_content_events": exact_count,
                "representative_copy_min_events": representative_min_events[
                    representative_key
                ],
                "representative_copy_max_events": representative_max_events[
                    representative_key
                ],
                "raw_eligible_files": raw_file_count,
                "unique_file_contents": exact_file_count,
                "raw_flagged_files": raw_flagged_count,
                "unique_flagged_contents": exact_flagged_count,
                "representative_copy_min_flagged_contents": (
                    representative_min_flagged[representative_key]
                ),
                "representative_copy_max_flagged_contents": (
                    representative_max_flagged[representative_key]
                ),
                "raw_percent_eligible_files_flagged": format_rate(
                    raw_flagged_count, raw_file_count, 100
                ),
                "exact_content_percent_flagged": format_rate(
                    exact_flagged_count, exact_file_count, 100
                ),
                "raw_flags_per_100_eligible_files": format_rate(
                    raw_row_count, raw_file_count, 100
                ),
                "canonical_events_per_100_eligible_files": format_rate(
                    canonical_count, raw_file_count, 100
                ),
                "exact_content_events_per_100_contents": format_rate(
                    exact_count, exact_file_count, 100
                ),
                "raw_flags_per_flagged_file": format_rate(
                    raw_row_count, raw_flagged_count
                ),
                "canonical_events_per_flagged_file": format_rate(
                    canonical_count, raw_flagged_count
                ),
                "exact_content_events_per_flagged_content": format_rate(
                    exact_count, exact_flagged_count
                ),
            }
        )

    eligible_weights = Counter()
    for row in manifest:
        weight = 1 / content_counts[row["sha256"]]
        eligible_weights[row["repository"], row["source_role"]] += weight
    flag_weights = Counter()
    for occurrences in exact_event_occurrences.values():
        weight = 1 / len(occurrences)
        for row in occurrences:
            flag_weights[row["repository"], row["antipattern"], row["source_role"]] += weight

    weighted_repository_rows = []
    for label, antipattern, role in units:
        for repository in names:
            if role == "all relevant files":
                eligible_files = sum(
                    eligible_weights[repository, source_role]
                    for source_role in SOURCE_ROLES
                )
                flags = sum(
                    count
                    for (repo, _, _), count in flag_weights.items()
                    if repo == repository
                )
            else:
                eligible_files = eligible_weights[repository, role]
                flags = flag_weights[repository, antipattern, role]
            weighted_repository_rows.append(
                {
                    "analysis_label": label,
                    "antipattern": antipattern,
                    "eligible_source_role": role,
                    "repository": repository,
                    "eligible_files": eligible_files,
                    "flags": flags,
                }
            )
    copy_sensitivity = {
        "duplicate_groups_with_inconsistent_event_sets": inconsistent_duplicate_groups,
        "exact_content_events_observed_in_only_some_copies": (
            partially_observed_exact_events
        ),
        "duplicate_groups_with_flagged_and_unflagged_copies": (
            groups_with_flagged_and_unflagged_copies
        ),
    }
    return (
        class_rows,
        weighted_repository_rows,
        content_counts,
        canonical_events,
        copy_sensitivity,
    )


def write_csv(path, fields, rows):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repositories", type=Path)
    parser.add_argument("allowlist", type=Path)
    parser.add_argument("flags", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path("analysis"))
    parser.add_argument("--reuse-manifest", action="store_true")
    args = parser.parse_args()

    rules = rule_values()
    digest = rule_digest(rules)
    assert digest == EXPECTED_RULE_SHA256, f"selection-rule SHA-256 changed: {digest}"

    thesis_root = args.allowlist.parent.parent
    notebooks_dir = thesis_root / "scripts"
    notebook_hashes = {}
    for filename in NOTEBOOKS:
        path = notebooks_dir / filename
        values = notebook_values(path)
        assert {name: values[name] for name in RULE_NAMES} == rules, f"selection rules differ: {path}"
        notebook_hashes[filename] = sha256(path)
    evaluation_values = notebook_values(notebooks_dir / "09-evaluate-prompting-strategy.ipynb")
    assert evaluation_values["ddl_indicator_phrases"] == DDL_INDICATOR_PHRASES

    names = read_allowlist(args.allowlist)
    name_to_project = {name: name.replace("/", "_") for name in names}
    assert len(set(name_to_project.values())) == len(names), "repository directory-name collision"
    expected_directories = {args.repositories / project for project in name_to_project.values()}
    assert all(path.is_dir() for path in expected_directories), "an allowlisted repository is missing"
    actual_directories = {path for path in args.repositories.iterdir() if path.is_dir()}
    excluded_directories = actual_directories - expected_directories
    assert len(excluded_directories) == EXPECTED_EXCLUDED_DIRECTORIES

    manifest_path = args.output_dir / "corpus_source_manifest.csv"
    if args.reuse_manifest:
        manifest = read_manifest(manifest_path, args.repositories)
    else:
        manifest = select_detector_sources(args.repositories, names)
    location_counts = Counter(row["source_location"] for row in manifest)
    assert dict(location_counts) == EXPECTED_SOURCE_LOCATIONS
    assert len(manifest) == EXPECTED_UNIQUE_FILES
    assert {args.repositories / row["repository"].replace("/", "_") for row in manifest} <= expected_directories

    frozen_fields, flags, alignments = align_flags(
        args.flags, args.repositories, name_to_project, manifest
    )
    project_results = args.flags.parent / "projects"
    reproduced, project_hashes = reproduce_merged_results(
        project_results, names, name_to_project, frozen_fields, flags
    )

    alignment_counts = Counter(row["fragment_alignment"] for row in alignments)
    span_supported_alignments = {
        "trimmed_exact",
        "whitespace_normalized_exact",
        "archived_fragment_within_span",
    }
    checks = {
        "allowlist_has_602_unique_names": len(names) == EXPECTED_REPOSITORIES,
        "allowlist_resolves_to_distinct_directories": len(expected_directories) == len(names),
        "excluded_directories_absent_from_frame": len(excluded_directories) == EXPECTED_EXCLUDED_DIRECTORIES,
        "source_location_counts_match": dict(location_counts) == EXPECTED_SOURCE_LOCATIONS,
        "unique_detector_selected_file_count_is_17988": len(manifest) == EXPECTED_UNIQUE_FILES,
        "selection_rule_digest_matches": digest == EXPECTED_RULE_SHA256,
        "corrected_notebooks_match_rules": True,
        "all_flags_resolve_to_allowlisted_source_files": all(
            row["source_file_exists"] == "true" for row in alignments
        ),
        "all_flags_are_in_source_frame": all(
            row["in_source_manifest"] == "true" for row in alignments
        ),
        "all_spans_are_in_bounds": all(row["span_in_bounds"] == "true" for row in alignments),
        "per_project_outputs_reproduce_frozen_csv": reproduced,
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    alignment_path = args.output_dir / "corpus_flag_alignment.csv"
    summary_path = args.output_dir / "corpus_phase1_summary.json"
    write_csv(manifest_path, MANIFEST_FIELDS, manifest)
    write_csv(alignment_path, ALIGNMENT_FIELDS, alignments)

    summary = {
        "phase": 1,
        "passed": all(checks.values()),
        "counts": {
            "allowlisted_repositories": len(names),
            "excluded_repository_directories": len(excluded_directories),
            "historical_reported_files": HISTORICAL_REPORTED_FILES,
            "target_generated_source_files": location_counts["target/generated-sources"],
            "unique_selected_files": len(manifest),
            "flags": len(flags),
            "source_locations": dict(location_counts),
            "source_roles": dict(Counter(row["source_role"] for row in manifest)),
            "flag_source_frame_status": dict(
                sorted(Counter(row["source_frame_status"] for row in alignments).items())
            ),
            "fragment_alignment": dict(sorted(alignment_counts.items())),
            "fragment_span_discrepancies": dict(
                sorted(
                    Counter(
                        (
                            "found_elsewhere_in_source_file"
                            if row["fragment_found_in_source_file"] == "true"
                            else "not_found_in_source_file"
                        )
                        for row in alignments
                        if row["fragment_alignment"] not in span_supported_alignments
                    ).items()
                )
            ),
        },
        "fragment_alignment_policy": (
            "Reported line spans are authoritative. Stored code fragments are best-effort "
            "diagnostics and do not affect phase acceptance."
        ),
        "fragment_normalization": (
            "Decode as UTF-8 when valid, otherwise Windows-1252 as specified by the detector's "
            "TextDecoder('latin1'); trim outer whitespace, then replace "
            "each whitespace run with one ASCII space. A stored fragment passes when it equals "
            "or is contained in the inclusive reported source span after normalization."
        ),
        "source_frame": (
            "Deduplicated files selected by the detector's **/*.java discovery and exact path/content "
            "filters at commit cf82fe56acb728f076df67279ff4a78a138996f3. Hidden paths and symbolic-link "
            "traversal are excluded."
        ),
        "checks": checks,
        "sha256": {
            "inputs": {
                str(args.allowlist): sha256(args.allowlist),
                str(args.flags): sha256(args.flags),
                "notebooks": notebook_hashes,
                "per_project_outputs": project_hashes,
            },
            "selection_rules": digest,
            "outputs": {
                manifest_path.name: sha256(manifest_path),
                alignment_path.name: sha256(alignment_path),
            },
        },
    }
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not summary["passed"]:
        raise SystemExit("Phase 1 acceptance checks failed; inspect corpus_phase1_summary.json")

    repository_rows, phase2_rows = phase2_tables(names, manifest, alignments)
    phase2_by_label = {row["analysis_label"]: row for row in phase2_rows}
    overall = phase2_by_label[OVERALL_LABEL]
    id_required = phase2_by_label["ID Required [generated schema]"]
    implicit_columns = phase2_by_label["Implicit Columns [application/query source]"]
    phase2_checks = {
        "all_flags_have_the_expected_class_source_role": set(
            (row["antipattern"], row["source_role"]) for row in alignments
        )
        == set(CLASS_SOURCE_ROLES),
        "any_class_has_7653_distinct_flagged_files": overall["unique_flagged_files"] == 7_653,
        "pooled_flagged_file_yield_is_42_5_percent": round(
            float(overall["percent_eligible_files_flagged"]), 1
        )
        == 42.5,
        "flagged_files_average_2_08_flags": round(float(overall["flags_per_flagged_file"]), 2)
        == 2.08,
        "id_required_has_3591_flagged_files": id_required["unique_flagged_files"] == 3_591,
        "id_required_has_about_1_flag_per_flagged_file": round(
            float(id_required["flags_per_flagged_file"]), 2
        )
        == 1.00,
        "implicit_columns_has_2607_flagged_files": implicit_columns["unique_flagged_files"]
        == 2_607,
        "implicit_columns_has_about_2_80_flags_per_flagged_file": round(
            float(implicit_columns["flags_per_flagged_file"]), 2
        )
        == 2.80,
        "density_decomposes_into_breadth_and_repetition": all(
            not row["flags"]
            or abs(
                row["flags"] / row["eligible_files"]
                - row["flagged_files"]
                / row["eligible_files"]
                * row["flags"]
                / row["flagged_files"]
            )
            < 1e-12
            for row in repository_rows
        ),
    }
    phase2_repository_path = args.output_dir / "corpus_phase2_by_repository.csv"
    phase2_summary_path = args.output_dir / "corpus_phase2_class_summary.csv"
    phase2_checks_path = args.output_dir / "corpus_phase2_summary.json"
    write_csv(phase2_repository_path, PHASE2_REPOSITORY_FIELDS, repository_rows)
    write_csv(phase2_summary_path, PHASE2_SUMMARY_FIELDS, phase2_rows)
    phase2_summary = {
        "phase": 2,
        "passed": all(phase2_checks.values()),
        "checks": phase2_checks,
        "rate_policy": (
            "Repository rates include repositories with eligible files and no flags as zero. "
            "Rates are blank when a repository has no eligible files. Repetition summaries "
            "include only repositories with a flagged file."
        ),
        "quartile_method": (
            "Python statistics.quantiles with n=4 and method='inclusive'; Q1 and Q3 bound "
            "the reported interquartile range."
        ),
        "sha256": {
            "inputs": {
                manifest_path.name: sha256(manifest_path),
                alignment_path.name: sha256(alignment_path),
            },
            "outputs": {
                phase2_repository_path.name: sha256(phase2_repository_path),
                phase2_summary_path.name: sha256(phase2_summary_path),
            },
        },
    }
    phase2_checks_path.write_text(
        json.dumps(phase2_summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if not phase2_summary["passed"]:
        raise SystemExit("Phase 2 acceptance checks failed; inspect corpus_phase2_summary.json")

    phase3_rows, concentration_rows, selected_top_deciles = phase3_tables(
        repository_rows, manifest
    )
    whole_corpus = {
        row["analysis_label"]: row
        for row in phase3_rows
        if row["scope"] == "all repositories"
    }
    without_top_decile = {
        row["analysis_label"]: row
        for row in phase3_rows
        if row["scope"] == "excluding highest-count decile"
    }
    concentration_by_label = {row["analysis_label"]: row for row in concentration_rows}
    stratum_rows = [
        row
        for row in phase3_rows
        if row["scope"] in {"small repositories", "medium repositories", "large repositories"}
    ]
    stratum_counts = {
        row["scope"].removesuffix(" repositories"): row["repositories"]
        for row in stratum_rows
        if row["analysis_label"] == OVERALL_LABEL
    }
    class_labels = [
        f"{antipattern} [{role}]" for antipattern, role in CLASS_SOURCE_ROLES
    ]
    pooled_ranking = sorted(
        class_labels,
        key=lambda label: -float(
            whole_corpus[label]["pooled_flags_per_100_eligible_files"]
        ),
    )
    repository_equal_ranking = sorted(
        class_labels,
        key=lambda label: -float(
            whole_corpus[label]["repository_equal_mean_flags_per_100_eligible_files"]
        ),
    )
    overall_concentration = concentration_by_label[OVERALL_LABEL]
    phase3_checks = {
        "whole_corpus_summaries_include_602_repositories": all(
            row["repositories"] == EXPECTED_REPOSITORIES for row in whole_corpus.values()
        ),
        "repository_without_flags_is_included": (
            whole_corpus[OVERALL_LABEL]["repositories"] == 602
            and whole_corpus[OVERALL_LABEL]["flagged_repositories"] == 601
        ),
        "fixed_size_strata_partition_the_corpus": stratum_counts
        == {"small": 473, "medium": 93, "large": 36},
        "strata_preserve_flags_and_eligible_files": all(
            sum(
                row[field]
                for row in stratum_rows
                if row["analysis_label"] == label
            )
            == whole_corpus[label][field]
            for label in whole_corpus
            for field in ("total_flags", "eligible_files")
        ),
        "top_decile_exclusion_preserves_flags_and_eligible_files": all(
            concentration_by_label[label][top_field]
            + without_top_decile[label][summary_field]
            == whole_corpus[label][summary_field]
            for label in whole_corpus
            for top_field, summary_field in (
                ("top_decile_flags", "total_flags"),
                ("top_decile_eligible_files", "eligible_files"),
            )
        ),
        "reported_overall_top_decile_flag_share_is_59_1_percent": round(
            float(overall_concentration["top_decile_flag_share_percent"]), 1
        )
        == 59.1,
        "all_requested_correlations_are_defined": all(
            row["spearman_raw_flags_vs_eligible_files"] for row in phase3_rows
        ),
        "each_top_decile_selection_is_reproducible": all(
            len(selected_top_deciles[label])
            == concentration_by_label[label]["top_decile_repositories"]
            for label in whole_corpus
        ),
        "cutoff_tie_bounds_contain_selected_results": all(
            float(row[minimum]) <= float(row[selected]) <= float(row[maximum])
            for row in concentration_rows
            for minimum, selected, maximum in (
                (
                    "top_decile_eligible_file_share_min_percent",
                    "top_decile_eligible_file_share_percent",
                    "top_decile_eligible_file_share_max_percent",
                ),
                (
                    "top_to_remaining_density_ratio_min",
                    "top_to_remaining_density_ratio",
                    "top_to_remaining_density_ratio_max",
                ),
            )
        ),
    }
    phase3_density_path = args.output_dir / "corpus_phase3_density_summary.csv"
    phase3_concentration_path = args.output_dir / "corpus_phase3_concentration.csv"
    phase3_summary_path = args.output_dir / "corpus_phase3_summary.json"
    write_csv(phase3_density_path, PHASE3_DENSITY_FIELDS, phase3_rows)
    write_csv(
        phase3_concentration_path,
        PHASE3_CONCENTRATION_FIELDS,
        concentration_rows,
    )
    top_flag_share = float(overall_concentration["top_decile_flag_share_percent"])
    top_file_share = float(overall_concentration["top_decile_eligible_file_share_percent"])
    min_top_file_share = float(
        overall_concentration["top_decile_eligible_file_share_min_percent"]
    )
    max_top_file_share = float(
        overall_concentration["top_decile_eligible_file_share_max_percent"]
    )
    density_ratio = float(overall_concentration["top_to_remaining_density_ratio"])
    min_density_ratio = float(overall_concentration["top_to_remaining_density_ratio_min"])
    max_density_ratio = float(overall_concentration["top_to_remaining_density_ratio_max"])
    new_headline_result_supported = top_flag_share > max_top_file_share and min_density_ratio > 1
    phase3_summary = {
        "phase": 3,
        "passed": all(phase3_checks.values()),
        "checks": phase3_checks,
        "size_strata": {
            "definition": (
                "Strata use total all-relevant files per repository. Small repositories have "
                "at most 31 files, medium repositories have 32-94 files, and large repositories "
                "have more than 94 files. Class densities use role-specific eligible-file counts."
            ),
            "counts": stratum_counts,
        },
        "methods": {
            "repository_equal": (
                "Means and percentiles include zero-flag repositories with eligible files. "
                "Repositories without eligible files have undefined density and are omitted."
            ),
            "percentiles": (
                "Python statistics.quantiles with method='inclusive'; the table reports P10, "
                "Q1, median, Q3, and P90."
            ),
            "correlation": (
                "Spearman rank correlation across all repositories in each scope, including "
                "zero counts. Python statistics.correlation averages tied ranks."
            ),
            "top_decile": (
                "Each analysis label has its own selection. We take the ceiling of 10% of "
                "repositories with at least one flag, ranked by raw flag count. Repository name "
                "breaks cutoff ties deterministically. The concentration table also gives bounds "
                "across every possible cutoff-tie selection."
            ),
        },
        "decision_gate": {
            "pooled_density_ranking": pooled_ranking,
            "repository_equal_mean_density_ranking": repository_equal_ranking,
            "rankings_are_identical": pooled_ranking == repository_equal_ranking,
            "overall_top_decile_flag_share_percent": top_flag_share,
            "overall_top_decile_eligible_file_share_percent": top_file_share,
            "overall_top_decile_eligible_file_share_min_percent": min_top_file_share,
            "overall_top_decile_eligible_file_share_max_percent": max_top_file_share,
            "overall_top_to_remaining_density_ratio": density_ratio,
            "overall_top_to_remaining_density_ratio_min": min_density_ratio,
            "overall_top_to_remaining_density_ratio_max": max_density_ratio,
            "new_headline_result_supported": new_headline_result_supported,
            "headline_result": (
                f"The highest-count decile contains {top_flag_share:.1f}% of flags and "
                f"between {min_top_file_share:.1f}% and {max_top_file_share:.1f}% of eligible "
                f"files across cutoff ties. Its flag density is between {min_density_ratio:.2f} "
                f"and {max_density_ratio:.2f} times that of the remaining repositories."
            ),
        },
        "sha256": {
            "inputs": {
                manifest_path.name: sha256(manifest_path),
                phase2_repository_path.name: sha256(phase2_repository_path),
            },
            "outputs": {
                phase3_density_path.name: sha256(phase3_density_path),
                phase3_concentration_path.name: sha256(phase3_concentration_path),
            },
        },
    }
    phase3_summary_path.write_text(
        json.dumps(phase3_summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    if not phase3_summary["passed"]:
        raise SystemExit("Phase 3 acceptance checks failed; inspect corpus_phase3_summary.json")

    (
        phase4_rows,
        weighted_repository_rows,
        content_counts,
        canonical_events,
        copy_sensitivity,
    ) = phase4_tables(names, manifest, alignments)
    _, exact_concentration_rows, exact_top_deciles = phase3_tables(
        weighted_repository_rows, manifest
    )
    phase4_by_label = {row["analysis_label"]: row for row in phase4_rows}
    exact_concentration_by_label = {
        row["analysis_label"]: row for row in exact_concentration_rows
    }
    exact_overall = phase4_by_label[OVERALL_LABEL]
    exact_overall_concentration = exact_concentration_by_label[OVERALL_LABEL]
    phase4_class_rows = [
        row for row in phase4_rows if row["analysis_label"] != OVERALL_LABEL
    ]

    def phase4_ranking(field, denominator=None):
        return [
            row["analysis_label"]
            for row in sorted(
                phase4_class_rows,
                key=lambda row: (
                    -float(row[field])
                    / (float(row[denominator]) if denominator else 1),
                    row["analysis_label"],
                ),
            )
        ]

    raw_total_ranking = phase4_ranking("raw_rows")
    canonical_total_ranking = phase4_ranking("canonical_events")
    exact_total_ranking = phase4_ranking("exact_content_events")
    raw_density_ranking = phase4_ranking("raw_flags_per_100_eligible_files")
    canonical_density_ranking = phase4_ranking(
        "canonical_events_per_100_eligible_files"
    )
    exact_density_ranking = phase4_ranking(
        "exact_content_events_per_100_contents"
    )
    raw_breadth_ranking = phase4_ranking("raw_percent_eligible_files_flagged")
    exact_breadth_ranking = phase4_ranking("exact_content_percent_flagged")
    raw_repetition_ranking = phase4_ranking("raw_flags_per_flagged_file")
    canonical_repetition_ranking = phase4_ranking(
        "canonical_events_per_flagged_file"
    )
    representative_min_total_ranking = phase4_ranking(
        "representative_copy_min_events"
    )
    representative_max_total_ranking = phase4_ranking(
        "representative_copy_max_events"
    )
    representative_min_breadth_ranking = phase4_ranking(
        "representative_copy_min_flagged_contents", "unique_file_contents"
    )
    representative_max_breadth_ranking = phase4_ranking(
        "representative_copy_max_flagged_contents", "unique_file_contents"
    )

    duplicate_groups = sum(count > 1 for count in content_counts.values())
    files_in_duplicate_groups = sum(
        count for count in content_counts.values() if count > 1
    )
    redundant_file_copies = len(manifest) - len(content_counts)
    flags_in_duplicate_files = sum(
        content_counts[row["source_sha256"]] > 1 for row in alignments
    )
    exact_top_flag_share = float(
        exact_overall_concentration["top_decile_flag_share_percent"]
    )
    exact_max_top_file_share = float(
        exact_overall_concentration["top_decile_eligible_file_share_max_percent"]
    )
    exact_min_density_ratio = float(
        exact_overall_concentration["top_to_remaining_density_ratio_min"]
    )
    concentration_interpretation_preserved = (
        exact_top_flag_share > exact_max_top_file_share
        and exact_min_density_ratio > 1
    )
    exact_implicit = phase4_by_label[
        "Implicit Columns [application/query source]"
    ]
    exact_id = phase4_by_label["ID Required [generated schema]"]
    phase2_headline_preserved = (
        float(exact_implicit["exact_content_events_per_100_contents"])
        > float(exact_id["exact_content_events_per_100_contents"])
        and float(exact_id["exact_content_percent_flagged"])
        > float(exact_implicit["exact_content_percent_flagged"])
        and float(exact_implicit["exact_content_events_per_flagged_content"])
        > float(exact_id["exact_content_events_per_flagged_content"])
    )
    representative_copy_phase2_headline_preserved = (
        exact_implicit["representative_copy_min_events"]
        / exact_implicit["unique_file_contents"]
        > exact_id["representative_copy_max_events"]
        / exact_id["unique_file_contents"]
        and exact_id["representative_copy_min_flagged_contents"]
        / exact_id["unique_file_contents"]
        > exact_implicit["representative_copy_max_flagged_contents"]
        / exact_implicit["unique_file_contents"]
        and exact_implicit["representative_copy_min_events"]
        / exact_implicit["representative_copy_max_flagged_contents"]
        > exact_id["representative_copy_max_events"]
        / exact_id["representative_copy_min_flagged_contents"]
    )
    representative_copy_total_ordering_preserved = all(
        phase4_by_label[higher]["representative_copy_min_events"]
        > phase4_by_label[lower]["representative_copy_max_events"]
        for higher, lower in zip(raw_total_ranking, raw_total_ranking[1:])
    )
    raw_and_canonical_ordering_preserved = (
        raw_total_ranking == canonical_total_ranking
        and raw_density_ranking == canonical_density_ranking
        and raw_repetition_ranking == canonical_repetition_ranking
    )
    exact_content_weighting_preserves_headlines = (
        phase2_headline_preserved and concentration_interpretation_preserved
    )
    phase4_checks = {
        "content_hashes_have_one_source_role": len(
            {(row["sha256"], row["source_role"]) for row in manifest}
        )
        == len(content_counts),
        "unique_contents_and_redundant_copies_reconstruct_manifest": (
            len(content_counts) + redundant_file_copies == len(manifest)
        ),
        "canonical_sensitivity_collapses_the_six_repeated_class_span_keys": (
            len(alignments) - len(canonical_events) == 6
        ),
        "exact_content_events_do_not_exceed_canonical_events": (
            int(exact_overall["exact_content_events"])
            <= int(exact_overall["canonical_events"])
        ),
        "repository_weights_preserve_one_unit_per_unique_content": abs(
            exact_overall_concentration["eligible_files"]
            - exact_overall["unique_file_contents"]
        )
        < 1e-9,
        "repository_weights_preserve_one_unit_per_exact_event": abs(
            exact_overall_concentration["total_flags"]
            - exact_overall["exact_content_events"]
        )
        < 1e-9,
        "raw_rows_and_canonical_events_preserve_substantive_ordering": (
            raw_and_canonical_ordering_preserved
        ),
        "exact_content_weighting_does_not_reverse_a_headline_result": (
            exact_content_weighting_preserves_headlines
        ),
        "representative_copy_event_ranges_preserve_total_ordering": (
            representative_copy_total_ordering_preserved
        ),
        "representative_copy_ranges_do_not_reverse_the_phase2_headline": (
            representative_copy_phase2_headline_preserved
        ),
    }
    phase4_table_path = args.output_dir / "corpus_phase4_exact_duplicate_sensitivity.csv"
    phase4_summary_path = args.output_dir / "corpus_phase4_summary.json"
    write_csv(phase4_table_path, PHASE4_CLASS_FIELDS, phase4_rows)
    phase4_summary = {
        "phase": 4,
        "passed": all(phase4_checks.values()),
        "checks": phase4_checks,
        "counts": {
            "relevant_file_occurrences": len(manifest),
            "unique_file_contents": len(content_counts),
            "duplicate_content_groups": duplicate_groups,
            "files_in_duplicate_groups": files_in_duplicate_groups,
            "files_in_duplicate_groups_percent": round(
                100 * files_in_duplicate_groups / len(manifest), 6
            ),
            "redundant_file_copies": redundant_file_copies,
            "redundant_file_copies_percent": round(
                100 * redundant_file_copies / len(manifest), 6
            ),
            "raw_flags_in_duplicate_files": flags_in_duplicate_files,
            "raw_flags_in_duplicate_files_percent": round(
                100 * flags_in_duplicate_files / len(alignments), 6
            ),
            "raw_rows": len(alignments),
            "canonical_events": len(canonical_events),
            "exact_content_events": int(exact_overall["exact_content_events"]),
            "representative_copy_min_events": int(
                exact_overall["representative_copy_min_events"]
            ),
            "representative_copy_max_events": int(
                exact_overall["representative_copy_max_events"]
            ),
            **copy_sensitivity,
        },
        "methods": {
            "duplicate_file": (
                "A relevant file is in a duplicate group when its SHA-256 occurs more than "
                "once. Files in duplicate groups counts every occurrence; redundant copies "
                "counts occurrences beyond the first in each group."
            ),
            "canonical_event": (
                "Canonical events are unique by repository, relative path, class, source role, "
                "and inclusive line span. This is a sensitivity definition: the six repeated "
                "keys have different explanations, and raw rows remain the published total."
            ),
            "exact_content_event": (
                "Exact-content events are unique by source SHA-256, class, source role, and "
                "inclusive line span. The reported count takes the union of observed events "
                "across byte-identical copies, so each content and occurrence span contributes "
                "at most once."
            ),
            "representative_copy_sensitivity": (
                "Some byte-identical copies have different detector outputs. The table therefore "
                "reports the minimum and maximum event and flagged-content totals obtained by "
                "selecting one physical copy within each content group."
            ),
            "repository_weighting": (
                "Each unique content contributes one file divided equally among its physical "
                "copies. Each exact-content event contributes one event divided equally among "
                "the canonical copied-file occurrences that report it. This preserves global "
                "unique-content totals without assigning a copied item to an arbitrary repository."
            ),
            "approximate_clones": (
                "Approximate clone detection was not run because exact duplicates did not "
                "reverse either headline result."
            ),
        },
        "ordering": {
            "raw_row_total_ranking": raw_total_ranking,
            "canonical_event_total_ranking": canonical_total_ranking,
            "exact_content_event_total_ranking": exact_total_ranking,
            "raw_pooled_density_ranking": raw_density_ranking,
            "canonical_pooled_density_ranking": canonical_density_ranking,
            "exact_content_pooled_density_ranking": exact_density_ranking,
            "raw_breadth_ranking": raw_breadth_ranking,
            "exact_content_breadth_ranking": exact_breadth_ranking,
            "raw_repetition_ranking": raw_repetition_ranking,
            "canonical_repetition_ranking": canonical_repetition_ranking,
            "representative_copy_min_total_ranking": representative_min_total_ranking,
            "representative_copy_max_total_ranking": representative_max_total_ranking,
            "representative_copy_total_ordering_preserved_for_all_selections": (
                representative_copy_total_ordering_preserved
            ),
            "representative_copy_min_breadth_ranking": (
                representative_min_breadth_ranking
            ),
            "representative_copy_max_breadth_ranking": (
                representative_max_breadth_ranking
            ),
            "raw_and_canonical_ordering_preserved": (
                raw_and_canonical_ordering_preserved
            ),
            "exact_total_ordering_preserved": raw_total_ranking == exact_total_ranking,
            "exact_density_ordering_preserved": (
                raw_density_ranking == exact_density_ranking
            ),
            "exact_breadth_ordering_preserved": (
                raw_breadth_ranking == exact_breadth_ranking
            ),
        },
        "concentration": {
            "raw": {
                key: overall_concentration[key]
                for key in PHASE3_CONCENTRATION_FIELDS
                if key not in {"analysis_label", "antipattern", "eligible_source_role"}
            },
            "exact_content_weighted": {
                key: (
                    round(value, 6) if isinstance(value, float) else value
                )
                for key, value in exact_overall_concentration.items()
                if key not in {"analysis_label", "antipattern", "eligible_source_role"}
            },
            "top_decile_repository_overlap": len(
                selected_top_deciles[OVERALL_LABEL]
                & exact_top_deciles[OVERALL_LABEL]
            ),
            "interpretation_preserved": concentration_interpretation_preserved,
        },
        "decision_gate": {
            "raw_row_and_canonical_event_ordering_preserved": (
                raw_and_canonical_ordering_preserved
            ),
            "phase2_breadth_repetition_headline_preserved": phase2_headline_preserved,
            "representative_copy_ranges_preserve_phase2_headline": (
                representative_copy_phase2_headline_preserved
            ),
            "phase3_size_and_excess_density_headline_preserved": (
                concentration_interpretation_preserved
            ),
            "exact_content_weighting_does_not_reverse_headlines": (
                exact_content_weighting_preserves_headlines
            ),
        },
        "sha256": {
            "inputs": {
                manifest_path.name: sha256(manifest_path),
                alignment_path.name: sha256(alignment_path),
                phase3_concentration_path.name: sha256(phase3_concentration_path),
            },
            "outputs": {
                phase4_table_path.name: sha256(phase4_table_path),
            },
        },
    }
    phase4_summary_path.write_text(
        json.dumps(phase4_summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print(
        json.dumps(
            {
                "phase1_passed": summary["passed"],
                "phase2_passed": phase2_summary["passed"],
                "phase3_passed": phase3_summary["passed"],
                "phase4_passed": phase4_summary["passed"],
                **summary["counts"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    if not phase4_summary["passed"]:
        raise SystemExit("Phase 4 acceptance checks failed; inspect corpus_phase4_summary.json")


if __name__ == "__main__":
    main()
