#!/usr/bin/env python3
"""Reconstruct the corpus source frame and measure flag breadth and repetition."""

import argparse
import ast
import csv
import glob
import hashlib
import json
import statistics
from collections import Counter, defaultdict
from pathlib import Path


EXPECTED_REPOSITORIES = 602
EXPECTED_EXCLUDED_DIRECTORIES = 43
HISTORICAL_REPORTED_FILES = 17_450
EXPECTED_SOURCE_LOCATIONS = {
    "src": 17_314,
    "target/generated-sources": 360,
    "other": 314,
}
EXPECTED_UNIQUE_FILES = 17_988
EXPECTED_FLAGS = 15_931
EXPECTED_RULE_SHA256 = "0e76695e8ff0705d6b8db74c500539d707926cbc8cb4df658ad4507d9d261b7b"
SOURCE_ROLES = ("generated schema", "application/query source")

CLASS_SOURCE_ROLES = (
    ("Implicit Columns", "application/query source"),
    ("ID Required", "generated schema"),
    ("Keyless Entry", "generated schema"),
    ("Fear of the Unknown", "generated schema"),
    ("Fear of the Unknown", "application/query source"),
    ("31 Flavors", "generated schema"),
    ("Poor Man's Search Engine", "application/query source"),
    ("Rounding Errors", "generated schema"),
)

EXCLUDED_PATH_FRAGMENTS = (
    "module-info.java",
    "package-info.java",
    "information_schema/InformationSchema.java",
    "information_schema/tables",
    "mysql/Mysql.java",
    "mysql/tables",
    "performance_schema/PerformanceSchema.java",
    "performance_schema/tables",
    "sys/Sys.java",
    "sys/tables",
    "FlywaySchemaHistory.java",
    "Databasechangelog.java",
    "Databasechangeloglock.java",
    "information_schema/Domains.java",
    "pg_catalog/PgCatalog.java",
    "pg_catalog/tables",
    "tables/Qrtz",
    "PgpArmorHeaders.java",
    "tables/Dblink",
    "tables/Each.java",
    "tables/Skeys.java",
    "tables/Svals.java",
)
INCLUDED_PHRASES = ("org.jooq", "Tables", "tables")
EXCLUDED_PHRASES = (
    "extends TableRecordImpl",
    "extends UpdatableRecordImpl",
    "extends org.jooq.impl.UpdatableRecordImpl",
    "extends CatalogImpl",
    "extends SchemaImpl",
    "extends UDTImpl",
    "extends UDTRecordImpl",
    "extends DAOImpl",
    "extends AbstractRoutine",
    "implements EnumType",
    "implements DeserializableJooqEnum",
    "public class Indexes",
    "public class Keys",
    "public class Routines",
    "public class Sequences",
    "public class Tables",
    "public class Domains",
    "class AbstractSpringDAOImpl",
    "extends AbstractSpringDAOImpl",
    "tables.pojos;",
    "tables.interfaces;",
    "Targeted by JavaCPP",
)
DDL_INDICATOR_PHRASES = (
    "This class is generated by jOOQ",
    "extends TableImpl",
    "extends org.jooq.impl.TableImpl",
)
RULE_NAMES = ("excluded_path_fragments", "included_phrases", "excluded_phrases")
NOTEBOOKS = (
    "25-count-relevant-files-in-full-set.ipynb",
    "051-select-sample-projects-corrected.ipynb",
    "09-evaluate-prompting-strategy.ipynb",
    "11-select-files-for-reannotation.ipynb",
    "23-count-relevant-files-in-validation-set.ipynb",
    "24-count-relevant-files-in-test-set.ipynb",
)
MANIFEST_FIELDS = (
    "repository",
    "relative_path",
    "source_location",
    "source_role",
    "bytes",
    "nonblank_loc",
    "sha256",
)
ALIGNMENT_FIELDS = (
    "flag_row",
    "repository",
    "project",
    "antipattern",
    "relative_path",
    "line_from",
    "line_to",
    "source_role",
    "source_sha256",
    "source_file_exists",
    "in_source_manifest",
    "source_frame_status",
    "span_in_bounds",
    "fragment_alignment",
    "fragment_found_in_source_file",
)
PROJECT_RESULT_FIELDS = (
    "Project",
    "Antipattern",
    "File",
    "Line from",
    "Line to",
    "Code fragment",
    "Explanation",
)
PHASE2_REPOSITORY_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "repository",
    "eligible_files",
    "flags",
    "flagged_files",
    "percent_eligible_files_flagged",
    "flags_per_100_eligible_files",
    "flags_per_flagged_file",
)
PHASE2_SUMMARY_FIELDS = (
    "analysis_label",
    "antipattern",
    "eligible_source_role",
    "repositories",
    "repositories_with_eligible_files",
    "flagged_repositories",
    "total_flags",
    "eligible_files",
    "unique_flagged_files",
    "all_relevant_files",
    "percent_eligible_files_flagged",
    "flags_per_100_eligible_files",
    "flags_per_flagged_file",
    "broad_flags_per_100_all_relevant_files",
    "repository_q1_percent_eligible_files_flagged",
    "repository_median_percent_eligible_files_flagged",
    "repository_q3_percent_eligible_files_flagged",
    "repository_q1_flags_per_100_eligible_files",
    "repository_median_flags_per_100_eligible_files",
    "repository_q3_flags_per_100_eligible_files",
    "flagged_repository_q1_flags_per_flagged_file",
    "flagged_repository_median_flags_per_flagged_file",
    "flagged_repository_q3_flags_per_flagged_file",
)


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rule_values():
    return {
        "excluded_path_fragments": EXCLUDED_PATH_FRAGMENTS,
        "included_phrases": INCLUDED_PHRASES,
        "excluded_phrases": EXCLUDED_PHRASES,
    }


def rule_digest(rules):
    payload = json.dumps(rules, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()


def notebook_values(path):
    values = {}
    notebook = json.loads(path.read_text(encoding="utf-8"))
    for cell in notebook["cells"]:
        try:
            tree = ast.parse("".join(cell.get("source", ())))
        except SyntaxError:
            continue
        for node in tree.body:
            if not isinstance(node, ast.Assign) or len(node.targets) != 1:
                continue
            target = node.targets[0]
            if isinstance(target, ast.Name) and target.id in (*RULE_NAMES, "ddl_indicator_phrases"):
                values[target.id] = tuple(ast.literal_eval(node.value))
    return values


def read_allowlist(path):
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    names = [row["name"] for row in rows]
    assert len(names) == EXPECTED_REPOSITORIES, f"expected 602 repositories, found {len(names)}"
    assert len(set(names)) == len(names), "allowlist repository names are not unique"
    return names


def source_location(relative_path):
    parts = Path(relative_path).parts
    if any(
        parts[index : index + 2] == ("target", "generated-sources")
        for index in range(len(parts) - 1)
    ):
        return "target/generated-sources"
    return "src" if "src" in parts else "other"


def source_row(name, project, path):
    relative_path = path.relative_to(project).as_posix()
    if not path.is_file() or any(part in relative_path for part in EXCLUDED_PATH_FRAGMENTS):
        return None
    raw = path.read_bytes()
    text = decode_java(raw)
    if not any(phrase in text for phrase in INCLUDED_PHRASES):
        return None
    if any(phrase in text for phrase in EXCLUDED_PHRASES):
        return None
    return {
        "repository": name,
        "relative_path": relative_path,
        "source_location": source_location(relative_path),
        "source_role": (
            "generated schema"
            if any(phrase in text for phrase in DDL_INDICATOR_PHRASES)
            else "application/query source"
        ),
        "bytes": len(raw),
        "nonblank_loc": sum(bool(line.strip()) for line in text.splitlines()),
        "sha256": hashlib.sha256(raw).hexdigest(),
    }


def select_detector_sources(repositories, names):
    manifest = {}
    for name in names:
        project = repositories / name.replace("/", "_")
        for filename in glob.glob(str(project / "**/*.java"), recursive=True):
            row = source_row(name, project, Path(filename))
            if row is not None:
                manifest[(name, row["relative_path"])] = row
    return sorted(manifest.values(), key=lambda row: (row["repository"], row["relative_path"]))


def read_manifest(path, repositories):
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        assert tuple(reader.fieldnames or ()) == MANIFEST_FIELDS
        rows = list(reader)
    manifest = {(row["repository"], row["relative_path"]): row for row in rows}
    assert len(manifest) == EXPECTED_UNIQUE_FILES
    refreshed = []
    for repository, relative_path in manifest:
        project = repositories / repository.replace("/", "_")
        row = source_row(repository, project, project / relative_path)
        assert row is not None, f"manifest file no longer passes detector filters: {project / relative_path}"
        refreshed.append(row)
    return sorted(refreshed, key=lambda row: (row["repository"], row["relative_path"]))


def decode_java(raw):
    try:
        return raw.decode("utf-8")
    except UnicodeDecodeError:
        return raw.decode("cp1252", errors="replace")


def normalize_whitespace(text):
    return " ".join(text.split())


def fragment_alignment(fragment, span):
    if fragment.strip() == span.strip():
        return "trimmed_exact"
    fragment = normalize_whitespace(fragment)
    span = normalize_whitespace(span)
    if fragment == span:
        return "whitespace_normalized_exact"
    if fragment and fragment in span:
        return "archived_fragment_within_span"
    if span and span in fragment:
        return "source_span_within_archived_fragment"
    return "mismatch"


def source_frame_status(path, relative_path, contents, source):
    if source is not None:
        return source["source_location"]
    reasons = []
    if "src" not in Path(relative_path).parts:
        reasons.append("outside_src_tree")
    if any(part in str(path) for part in EXCLUDED_PATH_FRAGMENTS):
        reasons.append("excluded_path_fragment")
    if not any(phrase in contents for phrase in INCLUDED_PHRASES):
        reasons.append("missing_included_phrase")
    if any(phrase in contents for phrase in EXCLUDED_PHRASES):
        reasons.append("contains_excluded_phrase")
    return "+".join(reasons) or "unexplained"


def align_flags(path, repositories, name_to_project, manifest):
    by_source = {(row["repository"], row["relative_path"]): row for row in manifest}
    text_cache = {}
    alignments = []
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        frozen_fields = tuple(reader.fieldnames or ())
        flags = list(reader)
    assert len(flags) == EXPECTED_FLAGS, f"expected 15,931 flags, found {len(flags)}"

    for flag_row, row in enumerate(flags, 1):
        name = row["project_name"]
        project_name = row["Project"]
        relative_path = Path(row["File"]).as_posix()
        expected_project = name_to_project.get(name)
        source = by_source.get((name, relative_path))
        in_manifest = source is not None and expected_project == project_name
        exists = False
        span_ok = False
        alignment = "not_checked"
        fragment_in_file = False
        frame_status = "not_checked"
        source_role = ""
        source_hash = ""
        if expected_project == project_name:
            project = repositories / project_name
            candidate = project / relative_path
            try:
                source_path = candidate.resolve(strict=True)
            except FileNotFoundError:
                source_path = None
            if source_path is not None:
                assert source_path.is_relative_to(project.resolve()), f"path escapes repository: {source_path}"
                exists = source_path.is_file()
            if exists:
                if source_path not in text_cache:
                    raw = source_path.read_bytes()
                    decoded_text = decode_java(raw)
                    text_cache[source_path] = (
                        decoded_text.splitlines(),
                        normalize_whitespace(decoded_text),
                        hashlib.sha256(raw).hexdigest(),
                        (
                            "generated schema"
                            if any(phrase in decoded_text for phrase in DDL_INDICATOR_PHRASES)
                            else "application/query source"
                        ),
                        source_frame_status(source_path, relative_path, decoded_text, source),
                    )
                lines, normalized_source, source_hash, source_role, frame_status = text_cache[source_path]
                normalized_fragment = normalize_whitespace(row["Code fragment"])
                fragment_in_file = bool(normalized_fragment and normalized_fragment in normalized_source)
                line_from = int(row["Line from"])
                line_to = int(row["Line to"])
                span_ok = 1 <= line_from <= line_to <= len(lines)
                if span_ok:
                    alignment = fragment_alignment(
                        row["Code fragment"], "\n".join(lines[line_from - 1 : line_to])
                    )
        alignments.append(
            {
                "flag_row": flag_row,
                "repository": name,
                "project": project_name,
                "antipattern": row["Antipattern"],
                "relative_path": relative_path,
                "line_from": row["Line from"],
                "line_to": row["Line to"],
                "source_role": source_role,
                "source_sha256": source_hash,
                "source_file_exists": str(exists).lower(),
                "in_source_manifest": str(in_manifest).lower(),
                "source_frame_status": frame_status,
                "span_in_bounds": str(span_ok).lower(),
                "fragment_alignment": alignment,
                "fragment_found_in_source_file": str(fragment_in_file).lower(),
            }
        )
    return frozen_fields, flags, alignments


def reproduce_merged_results(project_results, names, name_to_project, frozen_fields, flags):
    expected_paths = {project_results / f"{name_to_project[name]}.csv" for name in names}
    actual_paths = set(project_results.glob("*.csv"))
    assert actual_paths == expected_paths, "per-project result files do not match the allowlist"
    reconstructed = []
    hashes = {}
    for name in names:
        path = project_results / f"{name_to_project[name]}.csv"
        hashes[path.name] = sha256(path)
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.DictReader(handle)
            assert tuple(reader.fieldnames or ()) == PROJECT_RESULT_FIELDS, f"unexpected header: {path}"
            for row in reader:
                reconstructed.append((name, *(row[field] for field in PROJECT_RESULT_FIELDS)))
    frozen = [tuple(row[field] for field in frozen_fields) for row in flags]
    return Counter(reconstructed) == Counter(frozen), hashes


def format_rate(numerator, denominator, multiplier=1):
    return "" if not denominator else f"{multiplier * numerator / denominator:.6f}"


def quartiles(values):
    q1, _, q3 = statistics.quantiles(values, n=4, method="inclusive")
    return q1, statistics.median(values), q3


def phase2_tables(names, manifest, alignments):
    all_relevant_files = len(manifest)
    eligible = Counter((row["repository"], row["source_role"]) for row in manifest)
    flags = Counter(
        (row["repository"], row["antipattern"], row["source_role"])
        for row in alignments
    )
    flagged_files = defaultdict(set)
    for row in alignments:
        flagged_files[(row["repository"], row["antipattern"], row["source_role"])].add(
            row["relative_path"]
        )

    units = [
        (f"{antipattern} [{role}]", antipattern, role)
        for antipattern, role in CLASS_SOURCE_ROLES
    ]
    units.append(
        (
            "Any retained class [broad detector-output density]",
            "Any retained class",
            "all relevant files",
        )
    )
    repository_rows = []
    summary_rows = []
    for label, antipattern, role in units:
        rows = []
        for repository in names:
            if role == "all relevant files":
                file_count = sum(eligible[repository, source_role] for source_role in SOURCE_ROLES)
                flag_count = sum(
                    count
                    for (repo, _, _), count in flags.items()
                    if repo == repository
                )
                flagged = {
                    path
                    for (repo, _, _), paths in flagged_files.items()
                    if repo == repository
                    for path in paths
                }
            else:
                file_count = eligible[repository, role]
                flag_count = flags[repository, antipattern, role]
                flagged = flagged_files[repository, antipattern, role]
            row = {
                "analysis_label": label,
                "antipattern": antipattern,
                "eligible_source_role": role,
                "repository": repository,
                "eligible_files": file_count,
                "flags": flag_count,
                "flagged_files": len(flagged),
                "percent_eligible_files_flagged": format_rate(len(flagged), file_count, 100),
                "flags_per_100_eligible_files": format_rate(flag_count, file_count, 100),
                "flags_per_flagged_file": format_rate(flag_count, len(flagged)),
            }
            rows.append(row)
            repository_rows.append(row)

        eligible_rows = [row for row in rows if row["eligible_files"]]
        flagged_rows = [row for row in rows if row["flagged_files"]]
        breadth = [
            100 * row["flagged_files"] / row["eligible_files"] for row in eligible_rows
        ]
        density = [100 * row["flags"] / row["eligible_files"] for row in eligible_rows]
        repetition = [row["flags"] / row["flagged_files"] for row in flagged_rows]
        breadth_q1, breadth_median, breadth_q3 = quartiles(breadth)
        density_q1, density_median, density_q3 = quartiles(density)
        repetition_q1, repetition_median, repetition_q3 = quartiles(repetition)
        total_flags = sum(row["flags"] for row in rows)
        total_files = sum(row["eligible_files"] for row in rows)
        total_flagged_files = sum(row["flagged_files"] for row in rows)
        summary_rows.append(
            {
                "analysis_label": label,
                "antipattern": antipattern,
                "eligible_source_role": role,
                "repositories": len(rows),
                "repositories_with_eligible_files": len(eligible_rows),
                "flagged_repositories": len(flagged_rows),
                "total_flags": total_flags,
                "eligible_files": total_files,
                "unique_flagged_files": total_flagged_files,
                "all_relevant_files": all_relevant_files,
                "percent_eligible_files_flagged": format_rate(total_flagged_files, total_files, 100),
                "flags_per_100_eligible_files": format_rate(total_flags, total_files, 100),
                "flags_per_flagged_file": format_rate(total_flags, total_flagged_files),
                "broad_flags_per_100_all_relevant_files": format_rate(
                    total_flags, all_relevant_files, 100
                ),
                "repository_q1_percent_eligible_files_flagged": f"{breadth_q1:.6f}",
                "repository_median_percent_eligible_files_flagged": f"{breadth_median:.6f}",
                "repository_q3_percent_eligible_files_flagged": f"{breadth_q3:.6f}",
                "repository_q1_flags_per_100_eligible_files": f"{density_q1:.6f}",
                "repository_median_flags_per_100_eligible_files": f"{density_median:.6f}",
                "repository_q3_flags_per_100_eligible_files": f"{density_q3:.6f}",
                "flagged_repository_q1_flags_per_flagged_file": f"{repetition_q1:.6f}",
                "flagged_repository_median_flags_per_flagged_file": f"{repetition_median:.6f}",
                "flagged_repository_q3_flags_per_flagged_file": f"{repetition_q3:.6f}",
            }
        )
    return repository_rows, summary_rows


def write_csv(path, fields, rows):
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repositories", type=Path)
    parser.add_argument("allowlist", type=Path)
    parser.add_argument("flags", type=Path)
    parser.add_argument("--output-dir", type=Path, default=Path("analysis"))
    parser.add_argument("--reuse-manifest", action="store_true")
    args = parser.parse_args()

    rules = rule_values()
    digest = rule_digest(rules)
    assert digest == EXPECTED_RULE_SHA256, f"selection-rule SHA-256 changed: {digest}"

    thesis_root = args.allowlist.parent.parent
    notebooks_dir = thesis_root / "scripts"
    notebook_hashes = {}
    for filename in NOTEBOOKS:
        path = notebooks_dir / filename
        values = notebook_values(path)
        assert {name: values[name] for name in RULE_NAMES} == rules, f"selection rules differ: {path}"
        notebook_hashes[filename] = sha256(path)
    evaluation_values = notebook_values(notebooks_dir / "09-evaluate-prompting-strategy.ipynb")
    assert evaluation_values["ddl_indicator_phrases"] == DDL_INDICATOR_PHRASES

    names = read_allowlist(args.allowlist)
    name_to_project = {name: name.replace("/", "_") for name in names}
    assert len(set(name_to_project.values())) == len(names), "repository directory-name collision"
    expected_directories = {args.repositories / project for project in name_to_project.values()}
    assert all(path.is_dir() for path in expected_directories), "an allowlisted repository is missing"
    actual_directories = {path for path in args.repositories.iterdir() if path.is_dir()}
    excluded_directories = actual_directories - expected_directories
    assert len(excluded_directories) == EXPECTED_EXCLUDED_DIRECTORIES

    manifest_path = args.output_dir / "corpus_source_manifest.csv"
    if args.reuse_manifest:
        manifest = read_manifest(manifest_path, args.repositories)
    else:
        manifest = select_detector_sources(args.repositories, names)
    location_counts = Counter(row["source_location"] for row in manifest)
    assert dict(location_counts) == EXPECTED_SOURCE_LOCATIONS
    assert len(manifest) == EXPECTED_UNIQUE_FILES
    assert {args.repositories / row["repository"].replace("/", "_") for row in manifest} <= expected_directories

    frozen_fields, flags, alignments = align_flags(
        args.flags, args.repositories, name_to_project, manifest
    )
    project_results = args.flags.parent / "projects"
    reproduced, project_hashes = reproduce_merged_results(
        project_results, names, name_to_project, frozen_fields, flags
    )

    alignment_counts = Counter(row["fragment_alignment"] for row in alignments)
    span_supported_alignments = {
        "trimmed_exact",
        "whitespace_normalized_exact",
        "archived_fragment_within_span",
    }
    checks = {
        "allowlist_has_602_unique_names": len(names) == EXPECTED_REPOSITORIES,
        "allowlist_resolves_to_distinct_directories": len(expected_directories) == len(names),
        "excluded_directories_absent_from_frame": len(excluded_directories) == EXPECTED_EXCLUDED_DIRECTORIES,
        "source_location_counts_match": dict(location_counts) == EXPECTED_SOURCE_LOCATIONS,
        "unique_detector_selected_file_count_is_17988": len(manifest) == EXPECTED_UNIQUE_FILES,
        "selection_rule_digest_matches": digest == EXPECTED_RULE_SHA256,
        "corrected_notebooks_match_rules": True,
        "all_flags_resolve_to_allowlisted_source_files": all(
            row["source_file_exists"] == "true" for row in alignments
        ),
        "all_flags_are_in_source_frame": all(
            row["in_source_manifest"] == "true" for row in alignments
        ),
        "all_spans_are_in_bounds": all(row["span_in_bounds"] == "true" for row in alignments),
        "per_project_outputs_reproduce_frozen_csv": reproduced,
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    alignment_path = args.output_dir / "corpus_flag_alignment.csv"
    summary_path = args.output_dir / "corpus_phase1_summary.json"
    write_csv(manifest_path, MANIFEST_FIELDS, manifest)
    write_csv(alignment_path, ALIGNMENT_FIELDS, alignments)

    summary = {
        "phase": 1,
        "passed": all(checks.values()),
        "counts": {
            "allowlisted_repositories": len(names),
            "excluded_repository_directories": len(excluded_directories),
            "historical_reported_files": HISTORICAL_REPORTED_FILES,
            "target_generated_source_files": location_counts["target/generated-sources"],
            "unique_selected_files": len(manifest),
            "flags": len(flags),
            "source_locations": dict(location_counts),
            "source_roles": dict(Counter(row["source_role"] for row in manifest)),
            "flag_source_frame_status": dict(
                sorted(Counter(row["source_frame_status"] for row in alignments).items())
            ),
            "fragment_alignment": dict(sorted(alignment_counts.items())),
            "fragment_span_discrepancies": dict(
                sorted(
                    Counter(
                        (
                            "found_elsewhere_in_source_file"
                            if row["fragment_found_in_source_file"] == "true"
                            else "not_found_in_source_file"
                        )
                        for row in alignments
                        if row["fragment_alignment"] not in span_supported_alignments
                    ).items()
                )
            ),
        },
        "fragment_alignment_policy": (
            "Reported line spans are authoritative. Stored code fragments are best-effort "
            "diagnostics and do not affect phase acceptance."
        ),
        "fragment_normalization": (
            "Decode as UTF-8 when valid, otherwise Windows-1252 as specified by the detector's "
            "TextDecoder('latin1'); trim outer whitespace, then replace "
            "each whitespace run with one ASCII space. A stored fragment passes when it equals "
            "or is contained in the inclusive reported source span after normalization."
        ),
        "source_frame": (
            "Deduplicated files selected by the detector's **/*.java discovery and exact path/content "
            "filters at commit cf82fe56acb728f076df67279ff4a78a138996f3. Hidden paths and symbolic-link "
            "traversal are excluded."
        ),
        "checks": checks,
        "sha256": {
            "inputs": {
                str(args.allowlist): sha256(args.allowlist),
                str(args.flags): sha256(args.flags),
                "notebooks": notebook_hashes,
                "per_project_outputs": project_hashes,
            },
            "selection_rules": digest,
            "outputs": {
                manifest_path.name: sha256(manifest_path),
                alignment_path.name: sha256(alignment_path),
            },
        },
    }
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not summary["passed"]:
        raise SystemExit("Phase 1 acceptance checks failed; inspect corpus_phase1_summary.json")

    repository_rows, phase2_rows = phase2_tables(names, manifest, alignments)
    phase2_by_label = {row["analysis_label"]: row for row in phase2_rows}
    overall = phase2_by_label["Any retained class [broad detector-output density]"]
    id_required = phase2_by_label["ID Required [generated schema]"]
    implicit_columns = phase2_by_label["Implicit Columns [application/query source]"]
    phase2_checks = {
        "all_flags_have_the_expected_class_source_role": set(
            (row["antipattern"], row["source_role"]) for row in alignments
        )
        == set(CLASS_SOURCE_ROLES),
        "any_class_has_7653_distinct_flagged_files": overall["unique_flagged_files"] == 7_653,
        "pooled_flagged_file_yield_is_42_5_percent": round(
            float(overall["percent_eligible_files_flagged"]), 1
        )
        == 42.5,
        "flagged_files_average_2_08_flags": round(float(overall["flags_per_flagged_file"]), 2)
        == 2.08,
        "id_required_has_3591_flagged_files": id_required["unique_flagged_files"] == 3_591,
        "id_required_has_about_1_flag_per_flagged_file": round(
            float(id_required["flags_per_flagged_file"]), 2
        )
        == 1.00,
        "implicit_columns_has_2607_flagged_files": implicit_columns["unique_flagged_files"]
        == 2_607,
        "implicit_columns_has_about_2_80_flags_per_flagged_file": round(
            float(implicit_columns["flags_per_flagged_file"]), 2
        )
        == 2.80,
        "density_decomposes_into_breadth_and_repetition": all(
            not row["flags"]
            or abs(
                row["flags"] / row["eligible_files"]
                - row["flagged_files"]
                / row["eligible_files"]
                * row["flags"]
                / row["flagged_files"]
            )
            < 1e-12
            for row in repository_rows
        ),
    }
    phase2_repository_path = args.output_dir / "corpus_phase2_by_repository.csv"
    phase2_summary_path = args.output_dir / "corpus_phase2_class_summary.csv"
    phase2_checks_path = args.output_dir / "corpus_phase2_summary.json"
    write_csv(phase2_repository_path, PHASE2_REPOSITORY_FIELDS, repository_rows)
    write_csv(phase2_summary_path, PHASE2_SUMMARY_FIELDS, phase2_rows)
    phase2_summary = {
        "phase": 2,
        "passed": all(phase2_checks.values()),
        "checks": phase2_checks,
        "rate_policy": (
            "Repository rates include repositories with eligible files and no flags as zero. "
            "Rates are blank when a repository has no eligible files. Repetition summaries "
            "include only repositories with a flagged file."
        ),
        "quartile_method": (
            "Python statistics.quantiles with n=4 and method='inclusive'; Q1 and Q3 bound "
            "the reported interquartile range."
        ),
        "sha256": {
            "inputs": {
                manifest_path.name: sha256(manifest_path),
                alignment_path.name: sha256(alignment_path),
            },
            "outputs": {
                phase2_repository_path.name: sha256(phase2_repository_path),
                phase2_summary_path.name: sha256(phase2_summary_path),
            },
        },
    }
    phase2_checks_path.write_text(
        json.dumps(phase2_summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    print(
        json.dumps(
            {
                "phase1_passed": summary["passed"],
                "phase2_passed": phase2_summary["passed"],
                **summary["counts"],
            },
            indent=2,
            sort_keys=True,
        )
    )
    if not phase2_summary["passed"]:
        raise SystemExit("Phase 2 acceptance checks failed; inspect corpus_phase2_summary.json")


if __name__ == "__main__":
    main()
